version: "3.8"

services:
  backend:
    build:
      context: . # Dockerfile is in the root
    command: /usr/local/bin/django_runserver.sh # To automatically activate venv, make migrations, and runserver
    volumes:
      - ../backend:/home/user/Edulite/backend # Mount backend source code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=EduLite.settings
    # depends_on:
    #   - db # If we add a database service

  frontend:
    build:
      context: . # Dockerfile is in the root
    working_dir: /home/user/edulite/Frontend/EduLiteFrontend
    command: npm run dev -- --host # Ensure Vite listens on all interfaces and correct port
    volumes:
      - ../Frontend/EduLiteFrontend:/home/user/edulite/Frontend/EduLiteFrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend # So frontend waits for backend (loosely) or for service discovery

#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=edulite
#      - POSTGRES_USER=edulite_user
#      - POSTGRES_PASSWORD=yoursecurepassword

# volumes:
#  postgres_data:
